CREATE TABLE employe(
    id integer AUTO_INCREMENT,
    ecode varchar(100) comment "员工编号",
    ename varchar(100) comment "员工姓名",
    uid varchar(100) comment "身份证号",
    sex   int          comment "性别",
    ethnic varchar(100) comment "民族",
    birthday varchar(100) comment "出生年月",
    wenhua varchar(100) comment "文化成都",
    hunyin  varchar(100) comment "婚姻状况",
    jiguan  varchar(100) comment "籍贯",
    bumen   varchar(100) comment "所属部门",
    tell    varchar(100) comment "联系电话",
    workstart varchar(100) comment "到岗日期",
    workleave varchar(100) comment "离岗日期",
    zhiwu     varchar(100) comment "职务",
    status    varchar(100) comment "在职状态",
    bankname   varchar(100) comment "工资银行",
    bankno     varchar(100) comment "工资卡号",
    description text comment "身份证号",
    modified timestamp(6),
    created timestamp(6),
    PRIMARY KEY (id)
);